version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "8001:5432"
